[package]
name = "bst"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Generic binary search tree abstraction"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
bst_derive = []
