[workspace]
members = ["./*"]
resolver = "2"

[workspace.package]
authors = ["ajen"]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
criterion = "0.5.1"
rand = "0.8.5"
arrayvec = "0.7.2"
