[package]
name = "solutions"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true, optional = true }

[lib]
doctest = false
test = true

[features]
default = []
rand = ["dep:rand"]
