[workspace]

members = [
    "lc_tool",
    "solutions",
    "weekly",
]
default-members = ["solutions"]
resolver = "2"

# enable if thin binary is needed
#[profile.release]
#opt-level = 'z'
#lto = "thin"
#panic = 'abort'

[workspace.dependencies]
rand = "0.8"

[profile.dev]
incremental = true
