[workspace]

members = [
    "lc_tool",
    "solutions",
]
default-members = ["lc_tool"]

# enable if thin binary is needed
#[profile.release]
#opt-level = 'z'
#lto = "thin"
#panic = 'abort'

[profile.dev]
incremental = false
